### ISSUE TITLE
Support for MiniMatch???

### ISSUE THREAD

**Issue by DynConcepts** [chrisism/VSTS.Robocopy#3]
Would love to be able to specify  "**\bin\$(BuildConfiguration)\**" as the source...
Primary reason is to use in conjunction with RoboCopy ability to maintain the Modified timestamp on the files.....

**Comment by chrisism** [comment]
Unfortunately this task is simply a wrapper around Robocopy functionality. See https://technet.microsoft.com/nl-nl/library/cc733145(v=ws.10).aspx for all details. 
So, untill somebody has a way of translating minmatch to a way that robocopy understand this can not be implemented.

**Comment by DynConcepts** [comment]
@chrisism - That confirms what I believe regarding robocopy. I was actually hoping for a switch/option for "Preserve Timestamp".  I pulled down the source of the existing task, and started going through it, but it calls out to a function that [tl.copy] that I do not see a way to alter to pass additional parameters....
