### ISSUE TITLE
wen working with more then one file extension it fails  

### ISSUE THREAD

**Issue by amitkuzi** [chrisism/VSTS.Robocopy#4]
when using the property "Files to copy" with more then one filter like in robocopy it will not copy them . 

exsample: 
 Files to copy =' *.dll *.exe *.pdb *.config ' 
![capture](https://user-images.githubusercontent.com/1466186/35559245-e9885726-05b2-11e8-9497-b7b4bf4938ea.PNG)

**Comment by chrisism** [comment]
I do not think that Robocopy supports multiple wildcards, only multiple actual files. However, maybe you can use the /XF parameter to exclude the files you don't want.

To use the full capabilities of Robocopy, open up the 'Options' category and use the field 'Other Robocopy options'.
In the end the Robocopy Task is just a wrapper around the actual Robocopy functionality. Available options you can find at https://technet.microsoft.com/nl-nl/library/cc733145%28v=ws.10%29.aspx?f=255&MSPPError=-2147217396

**Comment by chrisism** [comment]
No solution available. Closing item.
