### ISSUE TITLE
multiple files wildcard is not working

### ISSUE THREAD

**Issue by melvinduc** [chrisism/VSTS.Robocopy#6]
When you are using multiple file wildcards (like *.exe *.dll), the wrapper is not function correctly. This is because the files parameter (in robocopytask.ps1) is declared as type string, but this must be of type array. I already fixed it, but I am not able to push a new branch & create a pull request (or I don't know how exactly). 
![capture](https://user-images.githubusercontent.com/8711565/41040280-7f906ac4-698b-11e8-88e4-cf45590f6c6e.PNG)

**Comment by melvinduc** [comment]
I've created a pull request

**Comment by chrisism** [comment]
Thank you, I will check it out.

**Comment by dahovey** [comment]
@chrisism Has this pull request been reviewed? I encountered the same issue and would appreciate update to extension. 

Thanks.

**Comment by chrisism** [comment]
@dahovey 
Just checked and merged, but still needs changes to comply with azure devops task schema. Will fix that part and release an update in a little moment after last tests.
